# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
tasks:
  - name: install rstudioinit
    init: |
      sudo apt-get update 
      sudo apt-get upgrade -y
      sudo apt-get intsall r-base -y 
      sudo apt-get install gdebi-core -y
      wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.12.1-402-amd64.deb
      sudo gdebi -n rstudio-server-2023.12.1-402-amd64.deb
      gp ports visibility 8787:public
      sudo adduser mgi
  - name: Open RStudio Tab
    command: gp preview $(gp url 8787) --external

ports:
  # RStudio port
  - port: 8787
    onOpen: notify
    visibility: public    
