image: hothman/mgi:1.0
tasks:
  - name: install rstudioinit
    init: |
      sudo apt-get update 
      sudo apt-get upgrade -y
      gp ports visibility 8787:public
      sudo adduser mgi

  - name: Open RStudio Tab
    command: gp preview $(gp url 8787) --external
             gp preview  $(gp url 8888) --external


ports:
  # RStudio port
  - port: 8787
    onOpen: notify
    visibility: public

  - port: 8888
    onOpen: notify
    visibility: public
