# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
tasks:
  - name: install rstudioinit
    init: |
      sudo apt-get update 
      sudo apt-get upgrade -ygp
      gp ports visibility 8787:public

ports:
  # RStudio port
  - port: 8787
    onOpen: notify
    visibility: public    
