# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: hothman/mgi:v0.1

tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'
  - name: initialize conda
    command: conda init
  - name: activate base env 
    command: . /home/gitpod/.bashrc 

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

