# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: 
	file: .gitpod.Dockerfile

tasks:
  - name: initialize base envirement
    command: source /home/gitpod/.bashrc 



