image: condaforge/mambaforge:latest
tasks: 
  - name: install packages
  init: | 
  mamba install r-base=4.1.3  r-tibble=3.2.1 bioconductor-dada2=1.22.0 \
  sudo bioconductor-phyloseq=1.38.0 r-readxl=1.4.2 r-ggplot2 r-cowplot=1.1.1 \
  r-patchwork bioconductor-microbiotaprocess=1.6.1 r-rcolorbrewer r-recommended \
  r-irkernel -y

