# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: rocker/rstudio 

init: |
  sudo apt-get update 
  sudo apt-get upgrade -y 
  gp ports visibility 8787:public


ports:
  # RStudio port
  - port: 8787
    onOpen: notify
    visibility: public    
