# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
tasks:
  - name: install rstudioinit
    init: |
      sudo apt-get update 
      sudo apt-get upgrade -y
      sudo apt-get install gdebi-core -y
      wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.12.1-402-amd64.deb
      sudo apt-get install r-base -y && sudo gdebi -n rstudio-server-2023.12.1-402-amd64.deb
      gp ports visibility 8787:public
      sudo adduser mgi
      su - mgi
      wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh \
      -O miniforge.sh && bash miniforge.sh \
      -b -p /home/${USER}/miniforge && rm miniforge.sh
  - name: Open RStudio Tab
    command: gp preview $(gp url 8787) --external

ports:
  # RStudio port
  - port: 8787
    onOpen: notify
    visibility: public    
